title: codewithcelso
author: Celso Inácio
email: falecom@celsoinacio.com.br
description: > # this means to ignore newlines until "show_exerpts:"
  Hi, my name is Celso. I am a brazilian software architect. I usually immerse my mind in computing, books and music. I've started to develop things since 9 years ago when i was a teenager and now i love to do this.
show_excerpts: true # set to true to show excerpts on the homepage


url: https://celsoinacio.com.br

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: blog-from-celso-inacio

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/ceelsoinacio
      icon: twitter-square
      color: cyan
    - url: https://github.com/ceelsoin
      icon: github-square
      color: purple
    - url: https://www.linkedin.com/in/ceelsoinacio/
      icon: linkedin
      color: blue

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  # avatar_source: github
  # github_username: ceelsoin
  #avatar_source: local
  #avatar_path: /assets/avatar.png

podcast:
  title: [title]
  description: [description]
  # url: /podcast.xml # podcast xml url
  author: [podcast author]
  email: [podcast email]
  image: [podcast logo url] # logo in 1400 – 3000 pixel
  language: [language] # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: [category] # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: [subcategory]
  type: [podcast type] # episodic | serial
  explicit: [explicit state] # true | false
  complete: [complete state] # 'yes' | 'no'
  block: [block state] # 'yes' | 'no'

# Build settings
theme: jekyll-dash

feed:
  path: /rss.xml

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-sitemap
 - liquid_pluralize
 - liquid_reading_time
 - jekyll-gist
