title: codewithcelso
author: Celso Inácio
email: falecom@celsoinacio.com.br
description: > # this means to ignore newlines until "show_exerpts:"
  Hi, I'm Celso, a passionate Brazilian software engineer who thrives on creating and exploring innovative solutions. I specialize in web engineering and work at Globo, Brazil's leading television company, where I'm shaping the future of their CMS with a cutting-edge serverless platform. Every challenge is an opportunity to learn and push boundaries, and I’m constantly inspired to build systems that make a real impact.
show_excerpts: true # set to true to show excerpts on the homepage


url: https://celsoinacio.com.br

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# polyglot
languages: ["en", "pt-BR"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: blog-from-celso-inacio

  # generate ooter
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/ceelsoinacio
      icon: twitter-square
      color: cyan
    - url: https://github.com/ceelsoin
      icon: github-square
      color: purple
    - url: https://www.linkedin.com/in/ceelsoinacio/
      icon: linkedin
      color: blue

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: ceelsoin

podcast:
  title: [title]
  description: [description]
  # url: /podcast.xml # podcast xml url
  author: [podcast author]
  email: [podcast email]
  image: [podcast logo url] # logo in 1400 – 3000 pixel
  language: [language] # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: [category] # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: [subcategory]
  type: [podcast type] # episodic | serial
  explicit: [explicit state] # true | false
  complete: [complete state] # 'yes' | 'no'
  block: [block state] # 'yes' | 'no'

# Build settings
theme: jekyll-dash

feed:
  path: /rss.xml

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-sitemap
 - liquid_pluralize
 - liquid_reading_time
 - jekyll-gist
 - jekyll-polyglot

