name: Build and Deploy

on:
  push:
    branches:
      - main  # Defina a branch principal do seu repositório aqui

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build --source ./src --destination ./dist
      - name: View root files
        run: ls -la
      - name: View dist/
        run: ls -la ./dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.   